### PR TITLE
[PR] The proj files have been updated to enable SourceLink

### PR DESCRIPTION
**Pull request by JTOne123**
CSProj files have been updated to enable SourceLink in your nuget
---

*[This pull request was created with an automated workflow]*

I noticed that your repository and Nuget package are important for our .NET community, but you still haven't enabled SourceLink.

**We have to take 2 steps:**
1) Please approve this pull request and make .NET a better place for .NET developers and their debugging.
2) **Then just upload the .snupkg file** to https://www.nuget.org/ (now you can find the snupkg file along with the .nuget file)

You can find more information about SourceLine at the following links  
https://github.com/dotnet/sourcelink
https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx

If you are interesting about this automated workflow and how it works  
https://github.com/JTOne123/GitHubMassUpdater

*If you notice any flaws, please comment and I will try to make fixes manually*

### CODE REVIEW

**Comment by meziantou** [comment]
Hi,

Have you seen any problem with these NuGet packages? According to NuGet Package Explorer, the NuGet packages are already compatible with source link.

image

**Comment by JTOne123** [comment]
yes, but you need to generate snuget to upload it to nuget.org

**Comment by meziantou** [comment]
Ok I see. I was uploading the old symbol format (symbols.nuget). As it requires some changes in the CI, it was easier to do it on my side. I've included you as a co-author of the commit https://github.com/meziantou/Meziantou.Framework/commit/2e52184ed5c7d4fcf2284877fb4541bcf478ea25

I'll publish new versions later today !

**Comment by JTOne123** [comment]
very cool, thanks

**Comment by meziantou** [comment]
The new packages have been published with the symbols. Thanks for your help :)

https://dev.azure.com/meziantou/GitHub%20projects/_build/results?buildId=5507&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7dae026f-9e99-5d65-075e-3f7579577f94

**Comment by meziantou** [comment]
A few points about your scripts:
- There is a typo in the description: SourceLine -> SourceLink
- It doesn't consider the Directory.Build.props (maybe there is not enough repositories to use them)
- It doesn't mention [my blog post about SourceLink](https://www.meziantou.net/how-to-debug-nuget-packages-using-sourcelink.htm) ;) (I will update it with the snupkg later today) 

Thanks for helping the .NET community to get better packages!

**Comment by JTOne123** [comment]
1. Thanks, fixed
2. Yes, I got a lot of "hate" related to this issue from "big" nugets
3. Awesome article, I have been sending it to the people who looking for additional help

No, thank you to you 🙌

**Comment by JTOne123** [comment]
Hello,

Do you know how do I can generate for Xamarin project?

I have to add this code

image

to platform-specific project

When I try to build then I get the error

image


Looks like <IncludeSymbols>true</IncludeSymbols>, <SymbolPackageFormat>snupkg</SymbolPackageFormat> are unknown tags

Maybe you have some advice?

the example of xamarin proj file
https://github.com/1iveowl/Plugin.SegmentedControl/blob/master/src/crossplatform/SegCtrl.iOS/SegCtrl.iOS.csproj

**Comment by meziantou** [comment]
I don't know which property controls the compilation options in a Xamarin project. You can use [MSBuild binary log viewer](https://www.meziantou.net/exploring-the-msbuild-log-using-the-binary-log-viewer.htm) to check the actual compilation parameter and see if it actually use the `IncludeSymbols` property or something else.

**Pull request closed without merging**
